# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_books', to='review.User'),
        ),
    ]
